// Mock data for development and demonstration

import type {
  Category,
  Establishment,
  Service,
  ServiceCategory,
  Professional,
  Review,
  Appointment,
  Customer,
} from '@/types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Cabelo',
    slug: 'cabelo',
    icon: '💇',
    description: 'Cortes, coloração, tratamentos capilares',
    imageUrl: '/images/categories/hair.jpg',
  },
  {
    id: '2',
    name: 'Barba',
    slug: 'barba',
    icon: '🧔',
    description: 'Barba, bigode e cuidados masculinos',
    imageUrl: '/images/categories/beard.jpg',
  },
  {
    id: '3',
    name: 'Unhas',
    slug: 'unhas',
    icon: '💅',
    description: 'Manicure, pedicure e nail art',
    imageUrl: '/images/categories/nails.jpg',
  },
  {
    id: '4',
    name: 'Estética',
    slug: 'estetica',
    icon: '✨',
    description: 'Limpeza de pele, tratamentos faciais',
    imageUrl: '/images/categories/aesthetics.jpg',
  },
  {
    id: '5',
    name: 'Massagem',
    slug: 'massagem',
    icon: '💆',
    description: 'Massagens relaxantes e terapêuticas',
    imageUrl: '/images/categories/massage.jpg',
  },
  {
    id: '6',
    name: 'Maquiagem',
    slug: 'maquiagem',
    icon: '💄',
    description: 'Maquiagem social, artística e noivas',
    imageUrl: '/images/categories/makeup.jpg',
  },
];

export const establishments: Establishment[] = [
  {
    id: '1',
    name: 'Studio Glamour',
    slug: 'studio-glamour',
    description: 'Salão de beleza premium com os melhores profissionais da cidade. Oferecemos serviços de corte, coloração, tratamentos capilares, manicure, pedicure e muito mais.',
    logo: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&h=400&fit=crop',
    address: 'Av. Paulista, 1000 - Bela Vista',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01310-100',
    phone: '(11) 99999-9999',
    email: 'contato@studioglamour.com',
    rating: 4.8,
    reviewCount: 256,
    priceRange: 3,
    categories: ['cabelo', 'unhas', 'maquiagem'],
    amenities: ['Wi-Fi', 'Estacionamento', 'Café', 'Ar condicionado'],
    workingHours: {
      monday: { isOpen: true, open: '09:00', close: '20:00' },
      tuesday: { isOpen: true, open: '09:00', close: '20:00' },
      wednesday: { isOpen: true, open: '09:00', close: '20:00' },
      thursday: { isOpen: true, open: '09:00', close: '21:00' },
      friday: { isOpen: true, open: '09:00', close: '21:00' },
      saturday: { isOpen: true, open: '09:00', close: '18:00' },
      sunday: { isOpen: false },
    },
    location: { lat: -23.5505, lng: -46.6333 },
    isFeatured: true,
    isOpen: true,
  },
  {
    id: '2',
    name: 'Barbearia Clássica',
    slug: 'barbearia-classica',
    description: 'A melhor barbearia tradicional com ambiente descontraído e profissionais experientes.',
    logo: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=1200&h=400&fit=crop',
    address: 'Rua Augusta, 500 - Consolação',
    city: 'São Paulo',
    state: 'SP',
    phone: '(11) 98888-8888',
    rating: 4.9,
    reviewCount: 189,
    priceRange: 2,
    categories: ['barba', 'cabelo'],
    amenities: ['Wi-Fi', 'Cerveja cortesia', 'Sinuca'],
    workingHours: {
      monday: { isOpen: true, open: '10:00', close: '20:00' },
      tuesday: { isOpen: true, open: '10:00', close: '20:00' },
      wednesday: { isOpen: true, open: '10:00', close: '20:00' },
      thursday: { isOpen: true, open: '10:00', close: '20:00' },
      friday: { isOpen: true, open: '10:00', close: '21:00' },
      saturday: { isOpen: true, open: '10:00', close: '18:00' },
      sunday: { isOpen: false },
    },
    location: { lat: -23.5537, lng: -46.6596 },
    isFeatured: true,
    isOpen: true,
  },
  {
    id: '3',
    name: 'Spa Serenidade',
    slug: 'spa-serenidade',
    description: 'Um oásis de tranquilidade no coração da cidade. Massagens, tratamentos faciais e corporais.',
    logo: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=1200&h=400&fit=crop',
    address: 'Rua Oscar Freire, 200 - Jardins',
    city: 'São Paulo',
    state: 'SP',
    phone: '(11) 97777-7777',
    rating: 4.7,
    reviewCount: 142,
    priceRange: 4,
    categories: ['massagem', 'estetica'],
    amenities: ['Wi-Fi', 'Sala de relaxamento', 'Chá', 'Robes'],
    workingHours: {
      monday: { isOpen: true, open: '08:00', close: '21:00' },
      tuesday: { isOpen: true, open: '08:00', close: '21:00' },
      wednesday: { isOpen: true, open: '08:00', close: '21:00' },
      thursday: { isOpen: true, open: '08:00', close: '21:00' },
      friday: { isOpen: true, open: '08:00', close: '21:00' },
      saturday: { isOpen: true, open: '09:00', close: '18:00' },
      sunday: { isOpen: true, open: '10:00', close: '16:00' },
    },
    location: { lat: -23.5629, lng: -46.6692 },
    isFeatured: true,
    isOpen: true,
  },
  {
    id: '4',
    name: 'Nail Design Studio',
    slug: 'nail-design-studio',
    description: 'Especialistas em unhas artísticas e alongamentos. As melhores técnicas do mercado.',
    logo: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=1200&h=400&fit=crop',
    address: 'Rua Haddock Lobo, 800 - Cerqueira César',
    city: 'São Paulo',
    state: 'SP',
    phone: '(11) 96666-6666',
    rating: 4.6,
    reviewCount: 98,
    priceRange: 3,
    categories: ['unhas'],
    amenities: ['Wi-Fi', 'Café', 'Revista'],
    workingHours: {
      monday: { isOpen: true, open: '09:00', close: '19:00' },
      tuesday: { isOpen: true, open: '09:00', close: '19:00' },
      wednesday: { isOpen: true, open: '09:00', close: '19:00' },
      thursday: { isOpen: true, open: '09:00', close: '19:00' },
      friday: { isOpen: true, open: '09:00', close: '19:00' },
      saturday: { isOpen: true, open: '09:00', close: '17:00' },
      sunday: { isOpen: false },
    },
    location: { lat: -23.5601, lng: -46.6700 },
    isFeatured: false,
    isOpen: true,
  },
];

export const serviceCategories: ServiceCategory[] = [
  {
    id: 'cat-1',
    name: 'Cabelo',
    description: 'Serviços para cabelos',
    services: [
      {
        id: 'srv-1',
        name: 'Corte Feminino',
        description: 'Corte personalizado com lavagem e finalização',
        duration: 60,
        price: 8000,
        categoryId: 'cat-1',
        categoryName: 'Cabelo',
        isPopular: true,
      },
      {
        id: 'srv-2',
        name: 'Corte Masculino',
        description: 'Corte moderno com acabamento na máquina',
        duration: 30,
        price: 5000,
        categoryId: 'cat-1',
        categoryName: 'Cabelo',
        isPopular: true,
      },
      {
        id: 'srv-3',
        name: 'Coloração',
        description: 'Coloração completa com produtos premium',
        duration: 120,
        price: 15000,
        categoryId: 'cat-1',
        categoryName: 'Cabelo',
      },
      {
        id: 'srv-4',
        name: 'Mechas/Luzes',
        description: 'Mechas ou luzes com técnica escolhida',
        duration: 180,
        price: 25000,
        categoryId: 'cat-1',
        categoryName: 'Cabelo',
      },
      {
        id: 'srv-5',
        name: 'Escova',
        description: 'Escova modeladora com finalização',
        duration: 45,
        price: 6000,
        categoryId: 'cat-1',
        categoryName: 'Cabelo',
        isPopular: true,
      },
      {
        id: 'srv-6',
        name: 'Hidratação',
        description: 'Tratamento de hidratação profunda',
        duration: 60,
        price: 7000,
        categoryId: 'cat-1',
        categoryName: 'Cabelo',
      },
      {
        id: 'srv-7',
        name: 'Progressiva',
        description: 'Alisamento progressivo completo',
        duration: 180,
        price: 30000,
        categoryId: 'cat-1',
        categoryName: 'Cabelo',
      },
    ],
  },
  {
    id: 'cat-2',
    name: 'Unhas',
    description: 'Serviços de manicure e pedicure',
    services: [
      {
        id: 'srv-8',
        name: 'Manicure',
        description: 'Manicure completa com esmaltação',
        duration: 45,
        price: 4000,
        categoryId: 'cat-2',
        categoryName: 'Unhas',
        isPopular: true,
      },
      {
        id: 'srv-9',
        name: 'Pedicure',
        description: 'Pedicure completa com esmaltação',
        duration: 60,
        price: 5000,
        categoryId: 'cat-2',
        categoryName: 'Unhas',
        isPopular: true,
      },
      {
        id: 'srv-10',
        name: 'Manicure + Pedicure',
        description: 'Combo completo mãos e pés',
        duration: 90,
        price: 8000,
        promotionalPrice: 7500,
        categoryId: 'cat-2',
        categoryName: 'Unhas',
      },
      {
        id: 'srv-11',
        name: 'Unhas em Gel',
        description: 'Aplicação de unhas em gel',
        duration: 90,
        price: 12000,
        categoryId: 'cat-2',
        categoryName: 'Unhas',
      },
      {
        id: 'srv-12',
        name: 'Nail Art',
        description: 'Decoração artística nas unhas',
        duration: 30,
        price: 3000,
        categoryId: 'cat-2',
        categoryName: 'Unhas',
      },
    ],
  },
  {
    id: 'cat-3',
    name: 'Estética',
    description: 'Tratamentos estéticos faciais e corporais',
    services: [
      {
        id: 'srv-13',
        name: 'Limpeza de Pele',
        description: 'Limpeza profunda com extração',
        duration: 90,
        price: 12000,
        categoryId: 'cat-3',
        categoryName: 'Estética',
        isPopular: true,
      },
      {
        id: 'srv-14',
        name: 'Design de Sobrancelhas',
        description: 'Design com pinça ou linha',
        duration: 30,
        price: 4000,
        categoryId: 'cat-3',
        categoryName: 'Estética',
        isPopular: true,
      },
      {
        id: 'srv-15',
        name: 'Depilação Facial',
        description: 'Depilação com cera no rosto',
        duration: 20,
        price: 2500,
        categoryId: 'cat-3',
        categoryName: 'Estética',
      },
    ],
  },
  {
    id: 'cat-4',
    name: 'Maquiagem',
    description: 'Serviços de maquiagem',
    services: [
      {
        id: 'srv-16',
        name: 'Maquiagem Social',
        description: 'Maquiagem para eventos e festas',
        duration: 60,
        price: 15000,
        categoryId: 'cat-4',
        categoryName: 'Maquiagem',
        isPopular: true,
      },
      {
        id: 'srv-17',
        name: 'Maquiagem Noiva',
        description: 'Maquiagem especial para noivas com teste',
        duration: 90,
        price: 35000,
        categoryId: 'cat-4',
        categoryName: 'Maquiagem',
      },
      {
        id: 'srv-18',
        name: 'Automaquiagem (Aula)',
        description: 'Aula de automaquiagem personalizada',
        duration: 120,
        price: 20000,
        categoryId: 'cat-4',
        categoryName: 'Maquiagem',
      },
    ],
  },
];

export const professionals: Professional[] = [
  {
    id: 'prof-1',
    name: 'Ana Silva',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    bio: 'Especialista em coloração e cortes femininos com mais de 10 anos de experiência.',
    rating: 4.9,
    reviewCount: 128,
    specialties: ['Coloração', 'Corte Feminino', 'Mechas'],
    yearsExperience: 10,
    isAvailable: true,
  },
  {
    id: 'prof-2',
    name: 'Carlos Santos',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    bio: 'Barbeiro especializado em cortes clássicos e modernos.',
    rating: 4.8,
    reviewCount: 95,
    specialties: ['Corte Masculino', 'Barba', 'Degradê'],
    yearsExperience: 8,
    isAvailable: true,
  },
  {
    id: 'prof-3',
    name: 'Mariana Costa',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    bio: 'Nail designer premiada, especialista em unhas artísticas.',
    rating: 5.0,
    reviewCount: 76,
    specialties: ['Manicure', 'Unhas em Gel', 'Nail Art'],
    yearsExperience: 6,
    isAvailable: true,
  },
  {
    id: 'prof-4',
    name: 'Juliana Mendes',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop',
    bio: 'Maquiadora profissional com formação internacional.',
    rating: 4.9,
    reviewCount: 112,
    specialties: ['Maquiagem Social', 'Maquiagem Noiva', 'Automaquiagem'],
    yearsExperience: 12,
    isAvailable: true,
  },
  {
    id: 'prof-5',
    name: 'Pedro Oliveira',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
    bio: 'Hair stylist com especialização em cortes modernos.',
    rating: 4.7,
    reviewCount: 68,
    specialties: ['Corte Feminino', 'Corte Masculino', 'Escova'],
    yearsExperience: 5,
    isAvailable: false,
  },
];

export const reviews: Review[] = [
  {
    id: 'rev-1',
    customerId: 'cust-1',
    customerName: 'Maria Fernanda',
    customerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=50&h=50&fit=crop',
    rating: 5,
    comment: 'Excelente atendimento! A Ana é maravilhosa, fez exatamente o que eu queria. Super recomendo!',
    services: ['Coloração', 'Corte Feminino'],
    professionalName: 'Ana Silva',
    createdAt: '2024-01-15T14:30:00Z',
  },
  {
    id: 'rev-2',
    customerId: 'cust-2',
    customerName: 'João Paulo',
    rating: 5,
    comment: 'Melhor corte que já fiz! Ambiente muito agradável e profissionais competentes.',
    services: ['Corte Masculino', 'Barba'],
    professionalName: 'Carlos Santos',
    createdAt: '2024-01-14T10:00:00Z',
    response: {
      text: 'Obrigado pelo feedback, João! Esperamos vê-lo novamente em breve!',
      createdAt: '2024-01-14T16:00:00Z',
    },
  },
  {
    id: 'rev-3',
    customerId: 'cust-3',
    customerName: 'Camila Rodrigues',
    rating: 4,
    comment: 'Muito bom! Só demorou um pouco mais do que o esperado, mas o resultado ficou lindo.',
    services: ['Unhas em Gel'],
    professionalName: 'Mariana Costa',
    createdAt: '2024-01-13T16:45:00Z',
  },
  {
    id: 'rev-4',
    customerId: 'cust-4',
    customerName: 'Beatriz Lima',
    rating: 5,
    comment: 'Minha maquiagem para o casamento ficou perfeita! Durou a festa toda. Juliana é incrível!',
    services: ['Maquiagem Noiva'],
    professionalName: 'Juliana Mendes',
    createdAt: '2024-01-12T11:20:00Z',
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'apt-1',
    status: 'confirmed',
    services: [
      { id: 'srv-1', name: 'Corte Feminino', duration: 60, price: 8000 },
      { id: 'srv-6', name: 'Hidratação', duration: 60, price: 7000 },
    ],
    professional: {
      id: 'prof-1',
      name: 'Ana Silva',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    },
    establishment: {
      id: '1',
      name: 'Studio Glamour',
      slug: 'studio-glamour',
      address: 'Av. Paulista, 1000 - Bela Vista',
      phone: '(11) 99999-9999',
    },
    date: '2024-02-01',
    time: '14:00',
    endTime: '16:00',
    totalPrice: 15000,
    totalDuration: 120,
    createdAt: '2024-01-20T10:00:00Z',
    confirmedAt: '2024-01-20T10:05:00Z',
  },
  {
    id: 'apt-2',
    status: 'pending',
    services: [
      { id: 'srv-8', name: 'Manicure', duration: 45, price: 4000 },
      { id: 'srv-9', name: 'Pedicure', duration: 60, price: 5000 },
    ],
    professional: {
      id: 'prof-3',
      name: 'Mariana Costa',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    },
    establishment: {
      id: '1',
      name: 'Studio Glamour',
      slug: 'studio-glamour',
      address: 'Av. Paulista, 1000 - Bela Vista',
      phone: '(11) 99999-9999',
    },
    date: '2024-02-05',
    time: '10:00',
    endTime: '11:45',
    totalPrice: 9000,
    totalDuration: 105,
    createdAt: '2024-01-22T15:30:00Z',
  },
  {
    id: 'apt-3',
    status: 'completed',
    services: [
      { id: 'srv-2', name: 'Corte Masculino', duration: 30, price: 5000 },
    ],
    professional: {
      id: 'prof-2',
      name: 'Carlos Santos',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    },
    establishment: {
      id: '2',
      name: 'Barbearia Clássica',
      slug: 'barbearia-classica',
      address: 'Rua Augusta, 500 - Consolação',
      phone: '(11) 98888-8888',
    },
    date: '2024-01-15',
    time: '16:00',
    endTime: '16:30',
    totalPrice: 5000,
    totalDuration: 30,
    createdAt: '2024-01-10T09:00:00Z',
    confirmedAt: '2024-01-10T09:10:00Z',
  },
  {
    id: 'apt-4',
    status: 'cancelled',
    services: [
      { id: 'srv-16', name: 'Maquiagem Social', duration: 60, price: 15000 },
    ],
    professional: {
      id: 'prof-4',
      name: 'Juliana Mendes',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop',
    },
    establishment: {
      id: '1',
      name: 'Studio Glamour',
      slug: 'studio-glamour',
      address: 'Av. Paulista, 1000 - Bela Vista',
      phone: '(11) 99999-9999',
    },
    date: '2024-01-18',
    time: '11:00',
    endTime: '12:00',
    totalPrice: 15000,
    totalDuration: 60,
    createdAt: '2024-01-08T14:00:00Z',
    cancelledAt: '2024-01-17T20:00:00Z',
    cancellationReason: 'Imprevisto pessoal',
  },
];

export const mockCustomer: Customer = {
  id: 'cust-1',
  name: 'Maria Fernanda Silva',
  email: 'maria.fernanda@email.com',
  phone: '(11) 99999-1234',
  avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
  createdAt: '2023-06-15T10:00:00Z',
  appointmentCount: 12,
  lastVisit: '2024-01-15T14:00:00Z',
  favoriteEstablishments: ['1', '2'],
  notificationPreferences: {
    email: true,
    sms: true,
    push: true,
    reminders: true,
    promotions: false,
  },
};

export const timeSlots = [
  '08:00', '08:30', '09:00', '09:30', '10:00', '10:30',
  '11:00', '11:30', '12:00', '12:30', '13:00', '13:30',
  '14:00', '14:30', '15:00', '15:30', '16:00', '16:30',
  '17:00', '17:30', '18:00', '18:30', '19:00', '19:30',
  '20:00', '20:30',
];

export function getAvailableSlots(date: Date): string[] {
  // Simulate some random unavailable slots
  const unavailableIndexes = new Set([2, 5, 8, 11, 14]);
  return timeSlots.filter((_, index) => !unavailableIndexes.has(index));
}

export function formatPrice(priceInCents: number): string {
  return `R$ ${(priceInCents / 100).toFixed(2).replace('.', ',')}`;
}

export function formatDuration(minutes: number): string {
  if (minutes < 60) {
    return `${minutes} min`;
  }
  const hours = Math.floor(minutes / 60);
  const remainingMinutes = minutes % 60;
  if (remainingMinutes === 0) {
    return `${hours}h`;
  }
  return `${hours}h ${remainingMinutes}min`;
}
